import isEmptyTextNode from './utils/isEmptyTextNode';
import convertNodeToElement from './convertNodeToElement';

/**
 * Processes the nodes generated by htmlparser2 and convert them all into React elements
 *
 * @param {Object[]} nodes List of nodes to process
 * @param {Function} transform Transform function to optionally apply to nodes
 * @returns {React.Element[]} The list of processed React elements
 */
export default function processNodes(nodes, transform) {

  return nodes
    // .filter(node => !isEmptyTextNode(node))
    .map((node, index) => {

      // return the result of the transform function if applicable
      let transformed;
      if (typeof transform === 'function') {
        console.log('typeof transform is function, node: ', node);
        transformed = transform(node, index);
        if (transformed === null || !!transformed) {
          console.log('if transformed === null or !!transformed: ', transformed);
          return transformed;
        }
      }

      // otherwise convert the node as standard
      console.log('otherwise normal conversion, node: ', node);
      return convertNodeToElement(node, index, transform);

    });

}
